# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
    ]
