# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='signup',
            name='emailid',
            field=models.EmailField(max_length=50),
        ),
    ]
