# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0003_auto_20190216_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='bloodgroup',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='signup',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
    ]
