# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-22 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0004_auto_20190216_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='city',
        ),
    ]
