# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0007_auto_20190310_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='donar_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailid', models.EmailField(max_length=254)),
                ('inbox', models.CharField(max_length=500)),
            ],
        ),
    ]
