# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-12 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0008_donar_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
