# Generated by Django 2.2.2 on 2019-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0012_auto_20191001_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register12',
            name='blood_group',
            field=models.CharField(max_length=128),
        ),
    ]
