# Generated by Django 2.2.2 on 2019-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0017_volunteer_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_apply',
            name='Pin_code',
            field=models.IntegerField(),
        ),
    ]
