# Generated by Django 2.2.2 on 2019-10-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood1', '0019_auto_20191006_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_apply',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
